x/evm/keeper/msg_server.go, x/evm/keeper/msg_server_test.go
Current Behaviour
If validators vote false on a poll, the pending deposit is deleted after the poll completed.
For validators who vote slightly late, they will get error for no deposit found for poll.
If the voting threshold has been met and additional votes are received they should not return an error
=> fix(evm):  do not return error when additional votes on a failed poll 

x/axelarnet/keeper/msg_server.go, x/axelarnet/keeper/msg_server_test.go
- continue the execution on error so the rest transfers are not blocked
- add more logging
=> feat(axelarnet): continue execution on error

x/evm/keeper/msg_server.go, x/evm/keeper/msg_server_test.go
Use poll state to check vote status. 
fix the `return error on failed vote` issue
=> refactor(evm): use poll state in vote message

x/evm/keeper/msg_server.go, x/evm/keeper/msg_server_test.go
Can't confirm chain
```
$ axelard tx evm confirm-chain avalanche --from validator
{"height":"1612","txhash":"D343773D2ADB880A60B176F6F0BA7346E08E854ED1693ED6EB3BE63E0DF408AC","codespace":"evm","code":2,"data":"","raw_log":"failed to execute message; message index: 0: could not retrieve revote locking period for chain avalanche: bridge error","logs":[],"info":"","gas_wanted":"200000","gas_used":"186934","tx":null,"timestamp":""}
```
Thanks to @jcs47 for help.
=> fix: confirm chain fail

x/tss/keeper/keeperSign.go
we have a common prefix for `sig` and `sign_queue`
I add this for now, we need an overhaul to solve this as we discussed before
=> fix(tss): add separator in getSigs iterator

x/tss/keeper/keeperSign.go, x/tss/keeper/keeperSign_test.go
We use keyinfo to get key type and role. Key info is not exported, which is a wise choice.
Upon import the new genesis, we try to get key info, which leads to error
=> fix(tss): use key in start sign

x/tss/keeper/keeperSign.go, x/tss/keeper/keeperSign_test.go
cherry pick #1075 to release 0.9.x
We use keyinfo to get key type and role. Key info is not exported, which is a wise choice.
Upon import the new genesis, we try to get key info, which leads to error
=> fix(tss): use key type in start sign (#1075)

x/axelarnet/client/cli/tx.go
There is an index-out-of-range error in the `register-asset` command of the axelarnet module.
=> fix(axelarnet): panic in CLI command

go.sum, x/evm/keeper/msg_server.go
Making the spelling of the chains consistent across modules
=> fix: make Link events consistent on axelarnet and evm

x/axelarnet/types/genesis.go
After generating a new genesis file, `axelard gentx` would fail because the validation of the collectors address at the axelarnet module was buggy
=> fix(axelarnet): collector address validation

.github/workflows/build-docker-image-and-binaries.yaml
- Context: sigstore is the latest tool from Linux Foundation for signing containers: https://www.sigstore.dev/
- Use `cosign` cmd from sigstore to perform signature using Github OIDC. More details:
+ https://github.com/sigstore/cosign/blob/main/KEYLESS.md
+ https://github.com/marketplace/actions/install-cosign
- The signed container can be verified later using `cosign` cmd.
- [NA] Unit tests
- [] Manual tests
- [] Documentation
- [NA] Connect epics/issues
- [NA ] Tag type of change
A sample test can be found in https://github.com/erain9/container-playground/blob/main/.github/workflows/build-container.yaml
All released container will be signed and can be verified by `cosign` from [sigstore](https://www.sigstore.dev/).
NA
=> feat(ci): sign released containers with sigstore

Dockerfile, cmd/axelard/cmd/root.go
For testing, we still want to be able to overwrite the keyring backend type with env variables. Because viper prioritizes flags over env variables, the backend flag mustn't be set with the value in order for the env variable to apply.
=> fix: set keyring backend flag, so it can still be overwritten

Dockerfile.binaries
This reverts commit d2e53233332fdcc4afcafc934d2404dfebae27bf.
=> chore: revert enable cgo for ledger support (#1160) [noci]

cmd/axelard/cmd/root_test.go, cmd/axelard/cmd/utils/utils.go, cmd/axelard/cmd/utils/utils_test.go
In case the flag value overwrite wasn't forced only the default value that's displayed to the user was overwritten, not the actual value that's used by the system.
=> fix: overwrite flag defaults correctly

utils/store.go, x/tss/keeper/keeperSign.go
Fixes Issue 1 from the Internal Audit report.
When iterating over a prefix, we don't require `_` to be present right after the prefix in the key. This can lead to an overlap in two keys. For e.g. when iterating with a prefix `state_key123`, both keys `state_key123_value` and `state_key1234_value` will be iterated over.
=> fix(keeper): append the delimiter to the iterator key

x/ante/ante.go
=> fix: only restrict validator from unbonding when holding key shares

cmd/axelard/cmd/vald/config/config.go
The automatic conversion of `string` in the `config.toml` to `AccAddress` doesn't work properly at the moment, so in the short term change the config to accept a `string` until this can be fixed.
=> fix: short term fee granter type replace (AccAddress -> string)

x/axelarnet/keeper/msg_server.go, x/axelarnet/types/events.go, x/bitcoin/keeper/msg_server.go, x/bitcoin/types/events.go, x/evm/keeper/msg_server.go, x/evm/types/events.go
=> feat: sourcechain and asset attributes in link events

cmd/axelard/cmd/vald/evm/rpc/rpcClient.go, cmd/axelard/cmd/vald/start.go, x/evm/types/config.go
Upon testing non-standard rpc methods (e.g., Moonbeam's `chain_getFinalizedHead`), ganache returns error code -32000 (server error) instead of -32601 (method not found error). In order to be able to continue using ganache for local testing (as well as to account for other possible situations where we wouldn't want to support non-standard rpc functionality), this PR adds a new field in evm config params called `rpc-module-support`, which allows vald to skip detecting non-standard rpc functionality.
=> feat(vald): new EVM config field

x/evm/types/params.go
=> fix: evm chain param validation

x/ante/ante.go
=> fix: skip logging during ante simulation

utils/queuer.go, utils/queuer_test.go, x/evm/keeper/chainKeeper.go, x/evm/keeper/keeper_test.go, x/evm/types/genesis.go, x/evm/types/types.go
=> feat(evm)!: prioritize executing burn commands

x/axelarnet/client/cli/tx.go
CLI command `confirm-deposit` at axelarnet did not match documention, thus still requiring 3 parameters
=> fix(axelarnet): cobra command to confirm deposits

.github/workflows/build-docker-image-and-binaries.yaml
- `v` is already part of ${SEMVER}
=> fix: binary versions for signing

x/snapshot/exported/types.go, x/snapshot/exported/types_test.go, x/tss/keeper/keeperSign.go, x/tss/keeper/keeperSign_test.go, x/tss/keeper/msg_server.go, x/tss/types/expected_keepers.go, x/tss/types/mock/expected_keepers.go
=> feat(tss): heartbeat should not affect multisig signing

cmd/axelard/cmd/vald/tss/tss.go, cmd/axelard/cmd/vald/tss/tss_test.go
The broadcaster can now send multiple messages per tx, and the heart beat code assumed there was always exactly one msg per tx. This fixes the heart beat code so any number of msgs can be sent, in particular multiple heart beats per tx.
=> fix: unmarshal heartbeat responses

x/evm/keeper/msg_server.go, x/evm/keeper/msg_server_test.go
=> fix(evm): the SignCommands should set command batch status to be signing

.github/workflows/build-docker-image-and-binaries.yaml
Run the https://github.com/axelarnetwork/axelar-core/blob/feat/build-matrix/.github/workflows/build-docker-image-and-binaries.yaml . It is a job triggered manually.
select branch feat/build-matrix.
ideally create a S3 and an ECR for testing purpose.
Enter a semantic tag, you should not use an existing tag (VERY IMPORTANT), if you do so you will overwrite the existing binaries/images. You can check the latest version in the S3 axelar-releases.
The job will run on 5 os/architectures (3 Linux, 2 Darwin).
The build of container images will occur only on Ubuntu/amd64 that is the only job that will run all the steps
In the 4 remaining jobs, all container related steps will be skipped.
To ensure that Ledger is supported, you can check in the test step of each job see …
=> feat: adding matrix build

x/evm/keeper/keeper_test.go
a three-letter key doesn't have enough randomness to ensure up to 50 generated keys do not collide
=> fix: test breaking due to key collisions

cmd/axelard/cmd/vald/broadcaster/broadcast_test.go, cmd/axelard/cmd/vald/broadcaster/refundable.go, cmd/axelard/cmd/vald/btc/btc.go, cmd/axelard/cmd/vald/btc/btc_test.go, cmd/axelard/cmd/vald/evm/evm.go, cmd/axelard/cmd/vald/evm/evm_test.go, cmd/axelard/cmd/vald/start.go, cmd/axelard/cmd/vald/tss/keygen.go, cmd/axelard/cmd/vald/tss/sign.go, cmd/axelard/cmd/vald/tss/tss.go
To prevent forgetting to wrap vald messages in refund requests a new broadcaster is introduced that does this for all messages
=> refactor: consolidate refund usage

Makefile
Fixing docker image build that has [failed](https://github.com/axelarnetwork/axelar-core/runs/5294278847?check_suite_focus=true)
Removing `populate-bytecode` from `make build` command as environment inside of docker image doesn't have `bash` available
Here is the same workflow with the fix that has [succeeded](https://github.com/axelarnetwork/axelar-core/actions/runs/1883919078)
=> fix(populate-bytecode): removing it from make build

cmd/axelard/cmd/vald/broadcaster/broadcast.go
Currently the broadcaster runs into a deadlock, because the length check of the backlog is done AFTER a peek into the backlog. Not only does peek not change the backlog length, but will also block on an empty backlog. Now it is done correctly after a pop from the backlog
=> fix: do the broadcast backlog length check at the correct location

cmd/axelard/cmd/vald/broadcaster/broadcast.go
=> fix: do the broadcast backlog length check at the correct location (#1336)

x/nexus/keeper/genesis_test.go
It was allowed that the max fee was zero and the fee rate nonzero, so fee info validation failed
=> fix(test): fix parameter space in genesis test

x/evm/keeper/querier.go
The response from `axelard q evm token-address [chain] --asset [denom]` would always return `status: false` even if the token was confirmed
=> fix(evm): token query response

Makefile
`goimports` should be relevant during development, not when building a binary
=> fix(build): remove goimports from `make build`

x/evm/keeper/grpc_query.go, x/evm/keeper/querier.go
the BurnerInfo query iterated over a marshalled response object instead of chain names
=> fix(evm): burnerInfo correctly iterates over chains

.github/workflows/take-snapshot.yaml, .github/workflows/testnet-catch-up.yml
-  Take backup pipeline allows you to take a testnet snapshot and tag it. The snapshot is uploaded from quicksync to S3 
- Catch up pipeline allows you to select a snapshot version and an axelard version to catch up
- Logs are forwarder from the host to Cloudwatch where you can apply filters
Run  take snapshot pipeline and check it is present in the S3 bucket
Run catchup pipeline check that the logs are forwarded to Cloudwatch where you apply filters
=> feat: add node catchup

utils/abci.go, utils/abci_test.go
Because of the added caching in our endblockers, events were not passed down to the base context when the endblocker was successful.
=> fix: emit events from cached end blocker

x/evm/keeper/vote_handler.go
related to #1439, we also have the issue with vote handler in v0.17. 
Event handling will be moved to endblocker in v0.18.
=> fix(evm): emit events from cached ctx

x/evm/types/types.go, x/evm/types/types_test.go
`-` is not forbidden in asset and symbol string, so could cause a duplicate command ID. Use `_` separator instead that is forbidden in strings.
=> fix(evm): use default separator for command ID

go.mod, go.sum, x/nexus/keeper/migrate.go, x/nexus/keeper/migrate_test.go, x/tss/keeper/migrate.go
Delete fee info registered for uaxl on EVM chains.
While not deleting uaxl fee info doesn't break anything, we should do it for consistency.
=> fix(nexus): delete uaxl fee info

x/evm/abci.go, x/evm/types/types.go, x/evm/types/types_test.go
1. Fix EVM command decode for transferOwnership/Operatorship
2. Improve logging during event process in EVM's endblocker
=> fix(evm): evm command decode for transferOwnership/Operatorship

go.mod, go.sum, x/snapshot/keeper/keeper.go, x/snapshot/keeper/keeper_test.go
Validators with zero weight don't do anything down the line and add edge cases so all processes need to repeatedly check for it. Instead, snapshots now don't include those validators anymore
=> feat: exclude participants with zero weight from snapshots

x/nexus/keeper/msg_server.go, x/snapshot/keeper/keeper.go, x/snapshot/keeper/keeper_test.go
- Don't allow chain maintainer registration by validators not in the active set
- Check if snapshot candidates are validators
=> fix: disallow unbonded chain maintainer registration

cmd/axelard/cmd/vald/multisig/keygen.go, x/multisig/types/msg_submit_pub_key.go
Revert to signing the sender/proxy address (which is unique for each validator) to verify the pub key being submitted. This stops one validator from broadcasting another validator's pubkey instead and cause them to lose rewards.
=> fix(multisig): sign sender address for pubkey authentication

x/multisig/keeper/keygen.go, x/multisig/keeper/rotation.go, x/multisig/keeper/rotation_test.go
=> fix(multisig): create private method setKey to avoid KeygenCompleted event emitted on key assignment and rotation

x/evm/types/codec.go, x/vote/exported/types.go, x/vote/keeper/poll_test.go
The poll struct has multiple `Any` fields, but only the result field was unpacked in `UnpackInterfaces`. In addition, the concrete metadata type in the evm module needed to be registered to the `ProtoMarshaler` interface
=> fix(vote)!: correctly unmarshal poll metadata

x/multisig/abci.go, x/multisig/abci_test.go, x/multisig/keeper/msg_server_test.go, x/multisig/types/keygen.go, x/multisig/types/signing.go, x/multisig/types/signing_test.go, x/multisig/types/types_test.go
Currently, expiry height is a block where no key/signatures can be submitted. But since we process the keygen/signing in the end blocker, this adds an extra block for completion that doesn't get counted in the grace period. Specifically, signing with grace period of 1 will take 2 blocks after threshold is achieved for handling by the end blocker. Instead, handle sessions expiring in the next block.
=> fix: handle mpc sessions in the end blocker of previous block on expiry

x/multisig/abci.go, x/multisig/abci_test.go, x/multisig/keeper/msg_server_test.go, x/multisig/types/keygen.go, x/multisig/types/signing.go, x/multisig/types/signing_test.go, x/multisig/types/types_test.go
Backport #1682 
* refactored code
* fix tests
=> fix: handle mpc sessions in the end blocker of previous block on expiry (#1682)

x/evm/keeper/chainKeeper.go, x/evm/keeper/keeper_test.go, x/evm/keeper/msg_server.go, x/evm/keeper/msg_server_test.go, x/evm/types/expected_keepers.go, x/evm/types/mock/expected_keepers.go
Add a sanity check to verify burner address that is being confirmed
=> fix(evm): check burner address in confirm deposit

go.mod, go.sum, x/evm/keeper/vote_handler.go, x/evm/keeper/vote_handler_test.go, x/vote/abci.go
It is possible that voters lose chain maintainer status before an existing poll completes. In that case, we need to exclude them from processing in the vote handler because their state has already been cleared.
=> fix(evm)!: ignore voters that are not chain maintainers

app/app.go, x/evm/keeper/baseKeeper.go
The params keeper holds existing subspaces in memory. However, EVM chains and their respective subspaces are created dynamically. This change ensures the params keeper is aware of all existing chain subspaces at start-up
=> fix(evm): load all existing chain subspaces at startup

x/axelarnet/keeper/coin.go
caught by e2e test, should lock ICS20 token with IBC denom (ibc/{hash}), not the base denom
=> fix(axelarnet)!: get escrow address with IBC denom

docs/cli/axelard_query_nexus_chains.md, x/nexus/client/cli/query.go
- Allow filtering the list of chains by status in nexus CLI query
=> fix(nexus): add status to chains cli query

x/axelarnet/abci.go, x/axelarnet/keeper/msg_server.go, x/axelarnet/module.go, x/evm/abci.go, x/evm/keeper/chainKeeper.go, x/evm/keeper/msg_server.go, x/evm/keeper/sig_handler.go, x/evm/keeper/vote_handler.go, x/multisig/abci.go, x/multisig/keeper/keygen.go, x/multisig/keeper/msg_server.go, x/multisig/keeper/rotation.go, x/multisig/keeper/signing.go, x/nexus/keeper/transfer.go, x/vote/keeper/msg_server.go, x/vote/types/vote_router_test.go
This replaces all uses of `EmitTypedEvent` in the codebase with the shorthand from #1776
=> refactor(utils): use emit event shorthand across the codebase

x/nexus/keeper/transfer.go
Add missing `amount` field to nexus `FeeDeducted` event, identified [here](https://github.com/axelarnetwork/axelar-core/pull/1771#discussion_r986593664).
=> fix(nexus): add missing amount field to nexus fee event

docs/cli/axelard_query_nexus_chains.md, x/nexus/client/cli/query.go
cherry-pick #1774 
- Add flags to nexus chains CLI query to filter by activated/deactivated status
=> fix(nexus): add status to chains cli query (#1774)

vald/state_test.go
By chance the random bytes in the current test are sometimes unmarshallable, making the test for wrong data format fail
=> test: make wrong data format test for state store deterministic

utils/abci.go
panic log should format the error string
=> fix(utils): panic log formatting

go.mod, go.sum
fix in rosetta implementation to pass validation, pointing to https://github.com/axelarnetwork/cosmos-sdk/commit/7d9818dc359a05ff04a4cbe6ff0d896b0e21aeda
=> chore: rosetta dependency change

utils/abci.go, vald/start.go, x/multisig/types/signing_test.go
backport #1796 
* fix(vald): log errors after cleanup
* use consistent panic stack trace logging
=> fix(vald): log errors after cleanup (#1796)

app/app.go, x/multisig/keeper/keygen.go, x/multisig/keeper/keygen_test.go, x/multisig/keeper/snapshotter.go, x/multisig/keeper/snapshotter_test.go, x/multisig/types/expected_keepers.go, x/multisig/types/mock/expected_keepers.go, x/reward/abci.go, x/reward/types/expected_keepers.go
Validators who have opted out of keygen should be excluded from reward distribution
=> fix(reward)!: don't reward validators who have opted out of keygen

x/evm/keeper/chainKeeper.go, x/nexus/keeper/keeper_test.go, x/nexus/keeper/transfer.go, x/nexus/keeper/transfer_test.go
- Add delimiter to prefix key used by paginated iterator
=> fix!: add delimiter to paginated kv store iterator by prefix

app/app.go, go.mod, go.sum
The module address is not allowed to send IBC transfers (which the module relies on) as long as it is on the bank keeper's blocked list. On the other hand, the axelarnet module does not need to keep the invariant `actual module balance == expected module balance`, since we never track that balance outside the bank keeper to begin with.
=> fix(axelarnet): remove axelarnet module address from bank keeper blocked list

x/nexus/keeper/msg_server.go
The logs in question are provoked by wrong user input, which should never be an `Error` level log.
=> chore(nexus): demote RegisterChainMaintainer logs from error to debug level

x/evm/keeper/chainKeeper.go, x/evm/keeper/migrate.go, x/evm/keeper/migrate_test.go, x/evm/module.go
the burner info key has capital letters in it, which is being ignored after the recent evm module refactoring. This means values from before the refactoring aren't found anymore. This migrates the old key scheme to a new one to make them available again.
=> fix(evm): migrate broken burner info key

vald/start.go, vald/start_test.go
We replace the job manager with an errgroup so the context all of vald jobs run under gets cancelled as soon as one of the jobs fails. This should allow vald to shut down and log the error instead of simply stalling. In particular, the context is going to get cancelled when there are no new blocks for a configurable length of time
=> fix(vald): introduce errgroup so vald stops when one if its processes fails

x/axelarnet/keeper/keeper.go, x/evm/keeper/baseKeeper.go, x/evm/keeper/chainKeeper.go, x/multisig/keeper/keeper.go, x/nexus/keeper/keeper.go, x/permission/keeper/keeper.go, x/reward/keeper/keeper.go, x/snapshot/keeper/keeper.go, x/vote/keeper/keeper.go
We decided to hold off on the key migrations, so this cleans up the as of new unused new keys in the keepers
=> refactor: remove unused new keys

go.mod, go.sum
non consensus breaking, only has changes for rosetta implementation.
replaced with [this commit]( https://github.com/axelarnetwork/cosmos-sdk/commits/v0.45.9-rosetta)
=> chore(rosetta): rosetta dependency update

go.mod, go.sum
The current implementation of the rosetta /balances endpoint returns all available coins on the network, including those with a balance of 0. To address this, we have modified the endpoint to only return owned coins, which should provide a clearer and more accurate representation of a user's account status. (https://github.com/axelarnetwork/cosmos-sdk/commit/221f540372f17cdfec161a970a1265f8b50b3027)
This change has been backported to v0.31
=> chore: rosetta update

.github/workflows/build-docker-image-and-binaries.yaml
Pin the previous version of `cosign`. The new version is breaking, and we should fix the cmd and test it out before updating to it.
=> fix: use previous cosign version

x/axelarnet/keeper/coin.go, x/axelarnet/keeper/coin_test.go, x/axelarnet/keeper/msg_server.go, x/axelarnet/keeper/msg_server_test.go, x/axelarnet/message_handler_test.go, x/axelarnet/types/expected_keepers.go, x/axelarnet/types/mock/expected_keepers.go, x/bank/keeper/keeper.go, x/bank/keeper/keeper_test.go, x/snapshot/keeper/genesis_test.go, x/snapshot/keeper/keeper.go, x/snapshot/keeper/keeper_test.go, x/snapshot/types/expected_keepers.go, x/snapshot/types/mock/expected_keepers.go
=> feat(bankK)!: strict balance check

x/axelarnet/keeper/hooks.go, x/axelarnet/keeper/hooks_test.go, x/axelarnet/types/types.go
=> fix(axelarnet)!: add/trim 0x prefix when checking contract address min deposit

go.mod, go.sum
cherry-pick rosetta changes from v0.45.11 to [v0.45.16](https://github.com/axelarnetwork/cosmos-sdk/commits/v0.45.16-rosetta)
=> chore(rosetta): port rosetta changes to v0.45.16

x/ante/ante.go, x/ante/types/expected_keepers.go
[AXE-1739](https://axelarnetwork.atlassian.net/browse/AXE-1739)
[AXE-1739]: https://axelarnetwork.atlassian.net/browse/AXE-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix!: ignore key shares for deactivated chains for unbonding checks

contract-version.json, go.mod, go.sum
Bump gateway version to `v6.1.0`. [AXE-1725](https://axelarnetwork.atlassian.net/browse/AXE-1725)
[AXE-1725]: https://axelarnetwork.atlassian.net/browse/AXE-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump gateway version

x/nexus/keeper/general_message.go, x/nexus/keeper/general_message_test.go, x/nexus/keeper/transfer.go
=> refactor(nexus): add the new methods for storing general messages in Nexus and set them to be processing

x/axelarnet/handler.go, x/axelarnet/keeper/msg_server.go, x/axelarnet/keeper/msg_server_test.go, x/axelarnet/types/expected_keepers.go, x/axelarnet/types/mock/expected_keepers.go, x/nexus/exported/types.go
=> feat(axelarnet)!: pick up the new methods for setting general messages in the msg_server and proposal handler

x/axelarnet/message_handler.go, x/axelarnet/message_handler_test.go, x/nexus/keeper/msg_dispatcher.go, x/nexus/keeper/msg_dispatcher_test.go, x/nexus/types/expected_keepers.go, x/nexus/types/mock/expected_keepers.go
=> feat(axelarnet/nexus)!: pick up the new methods for setting general messages in ibc message_handler and nexus msg_dispatcher

x/evm/keeper/chainKeeper.go, x/evm/keeper/vote_handler.go, x/evm/keeper/vote_handler_test.go, x/evm/types/expected_keepers.go, x/evm/types/mock/expected_keepers.go
=> feat(evm): route contract call via the nexus module

cmd/axelard/cmd/helpers.go, utils/encoding.go, utils/encoding_test.go, vald/sign.go, x/axelarnet/client/cli/tx.go, x/evm/keeper/grpc_query.go, x/evm/keeper/migrate.go, x/evm/types/params.go, x/evm/types/testutils/rand.go, x/evm/types/types.go
[AXE-2635]
[AXE-2635]: https://axelarnetwork.atlassian.net/browse/AXE-2635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: allow hex strings to be prefixed by 0x optionally in queries

x/nexus/keeper/wasm_message_route.go, x/nexus/keeper/wasm_message_route_test.go
=> fix(nexus)!: change the route request from nexus to router tagging from route_messages to route_messages_from_nexus

x/axelarnet/keeper/message_route.go
The sdk. context needs to be wrapped into a context.Context, so it can be correctly unpacked again by the ibc handler
=> fix: correctly wrap context in the nexus message route

x/axelarnet/client/cli/tx.go, x/evm/client/cli/tx.go, x/multisig/client/cli/tx.go, x/nexus/client/cli/tx.go, x/permission/client/cli/tx.go
The `ValidateBasic` function has been called in the `GenerateOrBroadcastTxWithFactory` function, so we no longer need to add the `ValidateBasic` function when writing Cli. Related PRs can be viewed at: https://github.com/cosmos/cosmos-sdk/pull/9236#discussion_r623803504
=> refactor: remove ValidateBasic in cli

Dockerfile, go.mod, go.sum
Update to latest wasmvm [patch](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-004.md)
=> chore: bump wasmvm version

vald/evm/evm.go, vald/evm/evm_test.go, vald/evm/rpc/client.go, vald/evm/rpc/ethereum.go, vald/evm/rpc/mock/client.go, vald/evm/rpc/mock/ethereum.go, x/evm/types/events.go
- **Revert "fix(vald): broadcast empty vote for failed txs (#2100) (#2102)"**
- **fix(vald): panic when confirming gateway txs and tx is not finalized (#2108)**
- **fix(vald): vote empty when the tx has failed (#2109)**
=> chore: backport #2107, #2108 and #2109

.github/workflows/build-docker-image-and-binaries.yaml
Cosign are changing their TUF Trust Root, need to update cosign binary for it work again. 
https://blog.sigstore.dev/tuf-root-update/
=> fix: update cosign version

app/app.go, app/app_test.go, app/export.go, app/keepers.go, app/wasm_test.go, x/ante/check_refund.go, x/ante/restricted_tx.go, x/ante/restricted_tx_test.go, x/permission/keeper/keeper.go, x/permission/keeper/keeper_test.go
The RestrictedTx ante handler assumes that messages always have a signer and panics when there are none. However, messages routed through the nexus gateway do not have signers, so this prevents routing from amplifier to core. With this fix wasm messages are treated as if they had a signer of the lowest access level.
=> fix(ante)!: ensure ante handlers can deal with no signers in msg

app/app.go
Remove wasm and ibc hooks store addition since they were added in `v0.35`
=> fix(app): remove wasm store migration

app/app.go, x/axelarnet/keeper/message_route.go, x/axelarnet/keeper/message_route_test.go, x/axelarnet/types/expected_keepers.go, x/axelarnet/types/mock/expected_keepers.go
When sending the mandatory dust amount for `GeneralMessage` message types, the denomination should be the one that is actually used for bonding tokens rather the the default native asset. This is because when instantiating an axelar network, the actually bond denom may not be the same as the default denom.
=> fix(axelarnet): replace native asset with bond denom for dust amount

.github/workflows/build-binaries-and-push-to-r2.yaml
=> ci: remove binary_file path from axelard builds on r2

app/app.go
[AXE-4862]
[AXE-4862]: https://axelarnetwork.atlassian.net/browse/AXE-4862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove wasm folder migration

Dockerfile
=> build: add bash to containers to make interactions in k8s easier

vald/evm/evm.go, vald/evm/rpc/client.go
=> fix(vald): extend type API to reduce underlying ambiguity

.github/workflows/build-binaries-and-push-to-r2.yaml
=> fix(ci): axelard r2 bucket indexing

x/nexus/keeper/lockable_asset.go, x/nexus/keeper/lockable_asset_test.go
=> fix(nexus): coin type should be ICS20 if the coin is from external cosmos chain

x/axelarnet/module.go, x/axelarnet/module_test.go
=> feat(axelarnet)!: refund from escrow address to IBC account

go.mod, go.sum
=> chore: replace wasmd in go.mod

app/app.go, x/axelarnet/keeper/migrate.go, x/axelarnet/keeper/migrate_test.go, x/axelarnet/keeper/msg_server.go, x/axelarnet/keeper/msg_server_test.go, x/axelarnet/module.go, x/axelarnet/types/expected_keepers.go, x/axelarnet/types/mock/expected_keepers.go
=> fix(axelarnet)!: retry failed transfer

app/app.go, app/migrate_module_account.go, app/migrate_module_account_test.go
=> feat(app)!: migrate pre-initialized module accounts

x/axelarnet/keeper/msg_server.go
=> fix(axelarnet)!: use AxelarIBCAccount when retry

go.mod, go.sum
Pull the fix at https://github.com/axelarnetwork/cosmos-sdk/pull/1
=> fix(sdk): valid dec range

go.mod, go.sum
=> chore: sdk deps update (#2217)

go.mod, go.sum
This pr updates wasmd and combet bft deps.
- wasmd pointed to [commit ](https://github.com/axelarnetwork/wasmd/commits/releases/v0.34.x/) contains CWA-2024-005 fix based on v0.34.1.
- combet bft upgraded to include [fixes](https://github.com/axelarnetwork/cometbft/commits/releases/v0.34.x/) for [ASA-2025-002](https://github.com/cometbft/cometbft/security/advisories/GHSA-r3r4-g7hq-pq4f) and [sanity check for proposed blocks size](https://github.com/cometbft/cometbft/pull/1408), based on v0.34.31.
=> chore!: update dependencies
