axelarnetwork/axelar-core

Makefile
scripts/build-binaries.sh

feat: enable ledger support in axelard

---

Makefile
scripts/build-binaries.sh

backport #987 
* feat: enable ledger support in axelard
* update binary script

feat: enable ledger support in axelard (#987)

---

.dockerignore

fix: version command returns empty because .git isn't mounted on docker build

---

x/axelarnet/keeper/msg_server.go

fix flow evm -> axelarnet for ibc tokens

fix(axelarnet): use origin chain in ICS20 conversion

---

x/ante/check_refund.go

Someone can wrap restricted txs as refundable msg to bypass authentication ante handler. This pr loops through all incoming msgs and reject unregistered refundable msgs

feat(ante): reject unregistered refundable msg

---

.github/workflows/build-latest-docker-image.yaml

feat(infra): tag latest images with sha for idempotent deploys

---

x/evm/keeper/genesis_test.go
x/evm/module.go
x/evm/types/genesis.go
x/evm/types/types.go

fix: the default evm genesis state is now valid

---

x/evm/keeper/genesis_test.go
x/evm/module.go
x/evm/types/genesis.go
x/evm/types/types.go

fix: the default evm genesis state is now valid (#1056)

---

x/tss/keeper/genesis.go

fix(tss): nil pointer during genesis import

---

x/evm/keeper/msg_server.go
x/evm/keeper/msg_server_test.go

fix: confirm chain fail (#1066)

---

x/axelarnet/keeper/keeper.go

fix(axelarnet): wrong getter prefix

---

x/axelarnet/keeper/keeper.go

fix(axelarnet): wrong getter prefix (#1069)

---

x/tss/keeper/keeperSign.go

cherry pick #1072  to releases-0.9.x

fix(tss): add separator in getSigs iterator

---

x/ante/ante.go

cherry pick #1071 to releases 0.9.x

fix(ante): check chain when unbond

---

cmd/axelard/cmd/genauth.go
cmd/axelard/cmd/gencrisis.go
cmd/axelard/cmd/gengov.go
cmd/axelard/cmd/genmint.go
cmd/axelard/cmd/genstaking.go
docs/cli/axelard_set-genesis-gov.md
docs/cli/axelard_set-genesis-mint.md
docs/cli/axelard_set-genesis-staking.md
x/axelarnet/types/genesis.go

chore(params): expose CLI for more genesis params

---

cmd/axelard/cmd/genaccount.go
cmd/axelard/cmd/genslashing.go
cmd/axelard/cmd/root.go
docs/cli/axelard.md
docs/cli/axelard_set-genesis-auth.md
docs/cli/axelard_set-genesis-crisis.md
docs/cli/toc.md
x/tss/types/params.go

Register the CLI commands and generate docs

fix(genesis): register cli commands and update params

---

x/evm/keeper/msg_server.go
x/evm/types/expected_keepers.go
x/evm/types/mock/expected_keepers.go

style(evm): log tx ID for key transfers

---

x/evm/keeper/msg_server.go
x/evm/types/expected_keepers.go
x/evm/types/mock/expected_keepers.go

Cherry-picking PR #1080 into release branch 0.9.x

style(evm): log tx ID for key transfers (#1080)

---

x/tss/types/params.go

fix(tss): update external multisig threshold

---

x/axelarnet/types/genesis_test.go
x/axelarnet/types/types.go
x/bitcoin/types/genesis_test.go
x/evm/types/genesis_test.go
x/nexus/keeper/genesis_test.go
x/nexus/types/genesis_test.go
x/permission/types/genesis_test.go
x/reward/types/genesis_test.go
x/snapshot/types/genesis_test.go
x/tss/module.go
x/tss/types/genesis.go
x/tss/types/genesis_test.go
x/vote/types/genesis_test.go

test(genesis): default genesis states should be valid and make nexus genesis test deterministic

---

app/app.go
docs/cli/axelard_tx_gov_submit-proposal_ibc-upgrade.md
docs/cli/axelard_tx_gov_submit-proposal_update-client.md
docs/cli/toc.md

feat(app): add IBC client upgrade proposal handler

---

x/reward/abci.go

feat(reward): split external chain rewards by consensus power

---

app/app.go
x/reward/abci.go
x/reward/types/expected_keepers.go
x/reward/types/mock/expected_keepers.go
x/snapshot/handler.go
x/snapshot/keeper/keeper.go
x/snapshot/keeper/msg_server.go
x/snapshot/module.go
x/snapshot/types/expected_keepers.go
x/tss/keeper/querier.go

fix(snapshot): remove chain maintainer on proxy deactivation

---

go.mod
go.sum
x/snapshot/exported/mock/types.go
x/tss/abci.go
x/tss/keeper/keeperSign.go
x/tss/keeper/msg_server.go

fix(tss): move multisig completion logic in the EndBlocker to avoid gas issue of the very last signature submitter

---

x/axelarnet/module.go
x/snapshot/exported/mock/types.go

genesis file validation was missing at the axelarnet module. Closes #1117

fix(axelarnet): genesis file validation

---

x/evm/keeper/chainKeeper.go
x/evm/keeper/genesis.go
x/evm/keeper/msg_server.go
x/evm/keeper/tss_router.go
x/evm/types/expected_keepers.go
x/evm/types/mock/expected_keepers.go
x/tss/abci.go
x/tss/keeper/msg_server.go

fix(evm): command batch re-signing

---

Dockerfile
Dockerfile.debug

chore: add user to dockerfiles

---

x/tss/keeper/keeper.go

fix: remove overlapping prefix

---

Dockerfile
Dockerfile.debug

chore(infra): add user and group ids in dockerfile

---

Dockerfile

feat: add jq in the dockerfile instead of installing later in the liveness check

---

Dockerfile
Dockerfile.debug

chore(infra): fix permissions issue on mounting

---

x/evm/types/types.go

fix(evm): token capacity can be zero

---

x/evm/types/params.go
x/nexus/types/params.go

fix(vote): update chain voting params

---

cmd/axelard/cmd/vald/evm/evm.go
cmd/axelard/cmd/vald/evm/evm_test.go
x/evm/types/events.go

fix(vald): change event attribute from burnAddress to depositAddress

---

.github/workflows/build-docker-image-and-binaries.yaml

fix(ci): fix the container image URL in dockerhub for cosign to sign

fix(ci): fix the container image URL in dockerhub for cosign to sign

---

.github/workflows/build-docker-image-and-binaries.yaml

fix(ci): fix the container image URL in dockerhub for cosign to sign (#1135)

---

.github/workflows/build-docker-image-and-binaries.yaml

fix: permissions for workflow not required, default scope is appropriate

---

.github/workflows/build-docker-image-and-binaries.yaml

added permissions and tested in playground this time.

fix: fix permissions for workflow, add contents, id-token and packages

---

.github/workflows/build-docker-image-and-binaries.yaml

fix: fix permissions for workflow, add contents, id-token and packages (#1141)

---

cmd/axelard/cmd/vald/start.go
docs/cli/axelard_vald-start.md

fix: use file backend for vald keyring

---

cmd/axelard/cmd/vald/start.go
docs/cli/axelard_vald-start.md

fix: use file backend for vald keyring (#1156)

---

Dockerfile.binaries

chore: enable cgo for ledger support

---

Dockerfile.binaries

chore: enable cgo for ledger support (#1160)

---

Dockerfile.binaries

chore: revert enable cgo for ledger support (#1160) (#1162)

---

x/axelarnet/keeper/msg_server.go

fix(axelarnet): potential underflow

---

cmd/axelard/cmd/vald/start.go

fix(vald): allow keyring type to be set via environment variable

---

Dockerfile
Dockerfile.debug

chore: update chain id

---

app/app.go

feat(app): enable feegrant

---

cmd/axelard/cmd/vald/config/config.go
cmd/axelard/cmd/vald/start.go
go.sum

chore: remove bitcoin from vald

---

.github/workflows/build-docker-image-and-binaries.yaml
.gitignore
Makefile
scripts/build-binaries.sh

fix: binaries don't have the correct version

---

.github/workflows/build-docker-image-and-binaries.yaml
.gitignore
Makefile
cmd/axelard/cmd/root_test.go
cmd/axelard/cmd/utils/utils.go
cmd/axelard/cmd/utils/utils_test.go
cmd/axelard/cmd/vald/config/config.go
cmd/axelard/cmd/vald/start.go
go.sum
scripts/build-binaries.sh

chore: backport commits from main with fixes for keyring dir, bitcoin node and version population

---

x/axelarnet/keeper/msg_server.go
x/axelarnet/keeper/msg_server_test.go

fix(axelarnet): route ibc skip axelar chain

---

Dockerfile
Dockerfile.debug
cmd/axelard/cmd/vald/start.go

chore: cherry pick keyring and default chain id commits

---

x/tss/types/msg_ack.go
x/tss/types/msg_submit_multisig_pubkey.go
x/tss/types/msg_submit_multisig_signatures.go

fix(tss): add validation of fields that cannot be empty slices

---

go.mod
go.sum

force packages with vulnerabilities to be replaced with fixed versions

chore: remove packages with vulnerabilities

---

x/tss/keeper/msg_server.go

- update validator check
- move state mutation after return

fix(tss): validator check in heartbeat

---

x/permission/keeper/msg_server.go

fix: don't overwrite registered accounts

---

x/reward/types/msg_refund.go

fix(refund): refund msg validation

---

x/nexus/keeper/migrate.go

fix: remove fmt.Printf

---

Dockerfile
Makefile

feat: allow building image with propagated user ids

---

cmd/axelard/cmd/vald/evm/evm.go
cmd/axelard/cmd/vald/evm/evm_test.go
cmd/axelard/cmd/vald/evm/main/main.go
cmd/axelard/cmd/vald/evm/rpc/mock/rpcClient.go
cmd/axelard/cmd/vald/evm/rpc/rpcClient.go
cmd/axelard/cmd/vald/evm/rpc/types.go
go.mod

feat(vald): moonbeam finality

---

x/axelarnet/keeper/msg_server.go
x/evm/keeper/msg_server.go
x/evm/types/types.go
x/tss/abci.go
x/tss/keeper/keeper.go

fix: include transfer ID in deposit logs (#1220)

---

cmd/axelard/cmd/vald/evm/rpc/rpcClient.go
cmd/axelard/cmd/vald/evm/rpc/types.go

feat(vald): handle non-standard json-rpc (#1235)

---

.github/workflows/build-latest-docker-image.yaml
Makefile

fix(workflow): build axelard with correct version tag

---

cmd/axelard/cmd/vald/tss/sign.go
x/tss/abci.go

fix(tss): wrong payload decoding and timeout

---

x/tss/abci.go

fix(tss): fix the bug where panic happens on multisig timeout

---

x/tss/abci.go

fix(tss): logger in abci.go

---

.github/PULL_REQUEST_TEMPLATE.md

docs: add 'Upgrade handler' checkbox for PRs

---

cmd/axelard/cmd/root_test.go
cmd/axelard/cmd/vald/broadcaster/broadcast.go
cmd/axelard/cmd/vald/broadcaster/broadcast_test.go
cmd/axelard/cmd/vald/broadcaster/types/interfaces.go
cmd/axelard/cmd/vald/broadcaster/types/mock/types.go
cmd/axelard/cmd/vald/btc/btc.go
cmd/axelard/cmd/vald/config/config.go
cmd/axelard/cmd/vald/evm/evm.go
cmd/axelard/cmd/vald/start.go
cmd/axelard/cmd/vald/tss/keygen.go
cmd/axelard/cmd/vald/tss/sign.go
cmd/axelard/cmd/vald/tss/tss.go
docs/cli/axelard_vald-start.md

(cherry picked from commit d19d32d8f331fde86fe2ae1ab1233be0fdb89c11)

feat: batch vald broadcasts when traffic is high (#1285)

---

x/evm/keeper/tss_router.go

fix(evm): command batch resign

---

cmd/axelard/cmd/root_test.go
cmd/axelard/cmd/vald/broadcaster/broadcast.go
cmd/axelard/cmd/vald/broadcaster/broadcast_test.go
cmd/axelard/cmd/vald/broadcaster/types/interfaces.go
cmd/axelard/cmd/vald/broadcaster/types/mock/types.go
cmd/axelard/cmd/vald/btc/btc.go
cmd/axelard/cmd/vald/config/config.go
cmd/axelard/cmd/vald/evm/evm.go
cmd/axelard/cmd/vald/start.go
cmd/axelard/cmd/vald/tss/keygen.go
cmd/axelard/cmd/vald/tss/sign.go
cmd/axelard/cmd/vald/tss/tss.go
docs/cli/axelard_vald-start.md

This reverts commit 0f4ceeaa2f901f7625b4a126caf3ae8acf87fbf8.

revert: "feat: batch vald broadcasts when traffic is high (#1285) (#1286)"

---

x/evm/keeper/tss_router.go

fix(evm): remove command batch status sanity check

---

Dockerfile
Dockerfile.debug

chore(docker): update chain ID env var

---

Dockerfile
Dockerfile.binaries
Dockerfile.protocgen

fix(docker): axelard version was not being set

---

x/evm/keeper/msg_server.go

Extend token confirmation event with attributes that are needed for axelar-eds

chore(evm): additional attributes in event

---

cmd/axelard/cmd/vald/start.go
docs/cli/axelard_vald-start.md

fix: allow overriding gas price in vald

---

.github/workflows/build-docker-image-and-binaries.yaml

feat: adding matrix build (#1319)

---

.github/CODEOWNERS

chore: add talal as codeowner for ci/cd stuff

---

.github/workflows/build-docker-image-and-binaries.yaml

fix: improve signing

---

.github/workflows/build-docker-image-and-binaries.yaml

feat: improve sha256 grep

---

x/evm/keeper/chainKeeper.go
x/evm/keeper/keeper_test.go

fix: stop prioritizing burn commands

---

x/ante/restricted_tx.go

chore: allow fee info registration from controller

---

x/evm/keeper/msg_server.go
x/evm/keeper/msg_server_test.go
x/evm/keeper/querier_test.go
x/evm/types/types.go
x/evm/types/types_test.go

feat: max gas cost for burnToken command differs by token type

---

docs/cli/axelard_tx_axelarnet_add-cosmos-based-chain.md
docs/cli/axelard_tx_nexus_deregister-chain-maintainer.md
docs/cli/axelard_tx_nexus_register-chain-maintainer.md
docs/cli/toc.md
x/axelarnet/client/cli/tx.go
x/nexus/client/cli/tx.go

fix: make native assets optional when adding cosmos chain

---

.github/workflows/build-docker-image-and-binaries.yaml
.github/workflows/build-latest-docker-image.yaml

fix(build): populate contract bytecode in workflow

---

.github/workflows/build-docker-image-and-binaries.yaml

Regroup all binary steps at the beginning of pipeline for having the binaries built before docker image.

feat: reorder deploy

---

README.md

fix: broken link to bug bounty

---

x/evm/keeper/grpc_query.go

fix(evm): fix query q evm address ethereum --key-role

---

x/evm/keeper/msg_server.go

fix(evm): wrong place for queueing the ApproveContractCall commands

---

x/evm/keeper/msg_server.go

fix(evm): wrong type of thing being pushed back to the contract call queue

---

x/evm/keeper/grpc_query.go
x/evm/keeper/grpc_query_test.go
x/evm/keeper/querier.go
x/evm/types/types.go
x/evm/types/types_test.go

fix(evm): query pending-commands when having command approveContractCallWithMint

---

Dockerfile.debug
Dockerfile.protocgen
README.md

fix: dockerfile debug go update

---

x/evm/abci.go
x/evm/abci_test.go
x/evm/keeper/chainKeeper.go
x/evm/keeper/msg_server.go

refactor(evm): set confirmed event on the source chain instead for gateway tx events

---

.github/workflows/go-generate.yaml

fix(go-generate): fixing bytecode download for older versions

---

contract-artifacts/version-config.json

chore(evm): bump contracts version to v3.1.1

---

cmd/axelard/cmd/vald/evm/evm.go

fix: remove redudant return

---

cmd/axelard/cmd/vald/config/config.go

feat(vald): increase default batch size limit from 15 to 250

---

go.mod
go.sum

fix(build): fix build warning for mac os 12 (#1429)

---

x/evm/keeper/vote_handler.go

(cherry picked from commit c135d4bbfe4443a91539a85823fff939562014c6)

fix(evm): emit events from cached ctx (#1445)

---

.github/workflows/take-snapshot.yaml

Fix indentation in take snapshot pipeline

fix: fix indentation

---

.github/workflows/release.yaml

temp gh action fix actions/checkout#762

fix(gh): fix gh action

---

.github/workflows/release.yaml

fix(gh): fix gh action (#1452)

---

app/app.go
x/ante/check_commission_rate.go
x/ante/check_commission_rate_test.go
x/ante/restricted_tx_test.go

feat(ante): check minimum validator commission rate

---

cmd/axelard/cmd/vald/tss/tss.go
x/tss/keeper/keeperKeygen.go
x/tss/keeper/keeperKeygen_test.go
x/tss/types/types.go

fix(tss): fix validator key query

---

x/nexus/exported/types.go
x/nexus/exported/types_test.go

- add ChainName type so we can restrict the max chain name

feat(nexus): length bounded type ChainName

---

utils/circular_buffer.go
utils/circular_buffer_test.go

Max size of the buffer can be changed dynamically and the buffer reacts accordingly the next time a value is added.

feat(utils): allow circular buffer to shrink when max size decreases

---

cmd/axelard/cmd/gencontracts.go
cmd/axelard/cmd/root.go
cmd/axelard/cmd/vald/broadcaster/broadcast.go
cmd/axelard/cmd/vald/broadcaster/broadcast_test.go
cmd/axelard/cmd/vald/healthcheck.go
testutils/utils.go
x/axelarnet/client/cli/tx.go
x/axelarnet/handler.go
x/axelarnet/keeper/msg_server_test.go
x/evm/client/cli/query.go
x/evm/client/rest/query.go
x/evm/keeper/grpc_query_test.go
x/evm/keeper/msg_server.go
x/evm/keeper/msg_server_test.go
x/evm/keeper/vote_handler.go
x/nexus/keeper/genesis.go
x/nexus/keeper/genesis_test.go
x/nexus/keeper/keeper_test.go
x/nexus/keeper/migrate_test.go
x/nexus/keeper/transfer_test.go
x/reward/keeper/msg_server_test.go
x/reward/keeper/reward_pool_test.go
x/tss/client/rest/query.go
x/tss/keeper/msg_server.go
x/vote/abci_test.go
x/vote/keeper/genesis_test.go

chore: fix golangci-lint errors wherever feasible

---

x/axelarnet/keeper/migrate.go
x/axelarnet/module.go

fix(axelarnet): add back a dummy migrate handler

---

x/axelarnet/keeper/migrate.go
x/axelarnet/module.go

fix(axelarnet): add back a dummy migrate handler (#1482)

---

x/vote/keeper/migrate.go

refactor(vote): reorganize read and write for migrate completed polls

---

go.mod
go.sum
x/evm/types/types.go
x/evm/types/types_test.go
x/nexus/keeper/migrate.go
x/nexus/keeper/migrate_test.go
x/tss/keeper/migrate.go

chore: backport evm command and migration fix

---

x/bitcoin/keeper/msg_server.go
x/tss/abci.go
x/tss/exported/types.go
x/tss/keeper/migrate_test.go

fix(tss): deprecated sig metadata was being emitted (#1489)

---

go.mod
go.sum
x/evm/types/params.go
x/reward/abci.go
x/vote/exported/types.go
x/vote/keeper/keeper.go
x/vote/keeper/keeper_test.go
x/vote/types/types.go
x/vote/types/types_test.go

fix(vote): filter out voters who do not have any voting power

---

go.mod
go.sum
x/evm/types/params.go
x/reward/abci.go
x/vote/exported/types.go
x/vote/keeper/keeper.go
x/vote/keeper/keeper_test.go
x/vote/types/types.go
x/vote/types/types_test.go

fix(vote)!: filter out voters who do not have any voting power (#1491)

---

cmd/axelard/cmd/vald/evm/evm.go

fix(vald): chain name parsing

---

Dockerfile.rosetta

feat: align go versions

---

x/evm/abci.go
x/evm/abci_test.go

feat(evm): drop fee for ContractCallWithToken

---

go.mod
go.sum
x/vote/types/types.go
x/vote/types/types_test.go

fix(vote)!: methods Poll.SetExpired and Poll.AllowOverride should have pointer receiver

---

cmd/axelard/cmd/vald/tss/keygen.go
cmd/axelard/cmd/vald/tss/sign.go
cmd/axelard/cmd/vald/tss/tss.go

* fix(vald): fix concurrent access to keys cache
* deps update
* utils update
* address comment

fix(vald): fix concurrent access to keys cache (#1555)

---

go.mod
go.sum
x/snapshot/exported/mock/types.go
x/snapshot/exported/types.go
x/snapshot/exported/types_test.go

feat(snapshot): add more functions to snapshot

---

.github/workflows/check-go-generate.yaml
.github/workflows/check-proto-generate.yaml

ci: split go and protobuf generate check into separate github actions

---

app/app.go
docs/cli/axelard_tx.md
docs/cli/axelard_tx_multisig.md
docs/cli/axelard_tx_multisig_start-keygen.md
docs/cli/toc.md
x/multisig/client/cli/tx.go
x/multisig/keeper/keeper.go
x/multisig/keeper/msg_server_test.go
x/multisig/module.go

feat(multisig): add module into app

---

x/multisig/types/keygen.go
x/multisig/types/signing.go
x/multisig/types/signing_test.go

feat(multisig): methods needed to perform multisig signing

---

cmd/axelard/cmd/vald/multisig/keygen.go
cmd/axelard/cmd/vald/multisig/mgr.go
cmd/axelard/cmd/vald/multisig/signing.go
cmd/axelard/cmd/vald/multisig/signing_test.go
cmd/axelard/cmd/vald/start.go
go.mod
go.sum

feat(vald): handle multisig signing

---

x/multisig/types/types.go
x/multisig/types/types_test.go

feat(multisig): require public key to be compressed

---

go.mod
go.sum
x/evm/abci.go
x/evm/abci_test.go
x/evm/keeper/baseKeeper.go

fix(evm): allow send token destination to be non evm chains

---

go.mod
go.sum
x/evm/abci.go
x/evm/abci_test.go
x/evm/keeper/chainKeeper.go
x/evm/module.go
x/evm/types/expected_keepers.go
x/evm/types/mock/expected_keepers.go
x/evm/types/types.go
x/evm/types/types_test.go

feat(evm): replace tss keeper with multisig keeper in the end blocker

---

x/multisig/keeper/msg_server_test.go
x/multisig/keeper/signing.go

feat(multisig): keeper sign takes in payload hash instead of payload

---

app/app.go
x/evm/handler.go
x/evm/keeper/chainKeeper.go
x/evm/keeper/keeper_test.go
x/evm/keeper/msg_server.go
x/evm/keeper/msg_server_test.go
x/evm/module.go
x/evm/types/events.go
x/evm/types/expected_keepers.go
x/evm/types/mock/expected_keepers.go
x/evm/types/types.go
x/evm/types/types_test.go
x/multisig/exported/mock/types.go
x/multisig/exported/types.go
x/multisig/keeper/rotation.go
x/multisig/keeper/rotation_test.go
x/multisig/types/keygen.go

feat(evm): handle weighted key transfer with the new multisig module

---

go.mod
go.sum
x/evm/abci.go
x/evm/keeper/msg_server.go
x/evm/keeper/msg_server_test.go

feat(evm): unblock command creation even during key transfer

---

x/evm/keeper/msg_server.go
x/evm/types/types.go

feat(evm): add command batch ID in sig metadata

---

docs/cli/axelard_query.md
docs/cli/axelard_query_multisig.md
docs/cli/axelard_query_multisig_key-id.md
docs/cli/axelard_query_multisig_next-key-id.md
docs/cli/toc.md
x/multisig/module.go
x/multisig/types/key.go

fix(multisg): expose query commands in the CLI

---

x/evm/keeper/grpc_query.go

fix(evm): fix slice initialization

---

cmd/axelard/cmd/vald/multisig/keygen.go
cmd/axelard/cmd/vald/multisig/signing.go

fix(vald): retain the key id suffix deriving keys

---

docs/cli/axelard_tx_evm_add-chain.md
docs/cli/toc.md
x/evm/client/cli/tx.go
x/evm/types/msg_add_chain.go

fix(evm): correct `add-chain` command validation

---

app/app.go

fix(multisig): add back evm sig router

---

x/multisig/types/codec.go

feat(multisig): register Multisig to ProtoMArshaler

---

x/evm/keeper/grpc_query.go
x/multisig/exported/types.go
x/multisig/types/types.go

fix(evm): transform signature

---

x/multisig/keeper/keygen.go
x/multisig/keeper/rotation.go
x/tss/keeper/migrate.go

fix(multisig): convert utils.AppendStr and utils.KeyFromStr to utils.LowerCaseKey

---

x/vote/keeper/poll.go

fix(vote): tally logger

---

go.mod
go.sum
x/evm/keeper/migrate.go
x/evm/keeper/migrate_test.go
x/evm/module.go
x/evm/types/expected_keepers.go
x/evm/types/mock/expected_keepers.go

feat(evm): command batch signature migration

---

docs/cli/axelard_query_evm.md
docs/cli/axelard_query_evm_event.md
docs/cli/toc.md
x/evm/client/cli/query.go

fix(evm): add query event

---

.github/workflows/next-release-version.yaml
go.mod
go.sum

chore: add dry run release job

---

.github/workflows/release-dry-run.yaml

chore: dry run release verbose

---

sdk-utils/broadcast/broadcast_test.go
vald/evm/evm.go
vald/evm/evm_test.go
x/evm/keeper/baseKeeper.go

fix(vald): validate confirmation events

---

README.md

chore: misc readme change

---

.github/workflows/enforce-evm-migration.yaml

ci(check): update git diff syntax in `Ensure EVM module migration when bytecode changes` check (#1674)

---

x/evm/types/types.go

chore(evm): bring approveContractCall&approveContractCallWithMint gas estimate from 120k down to 100k

---

x/evm/types/types.go

chore(evm): bring mintToken gas estimate from 150k down to 100k (#1678)

---

x/evm/types/types.go

chore(evm): bring approveContractCall&approveContractCallWithMint gas estimate from 120k down to 100k (#1680)

---

.github/workflows/build-docker-image-and-binaries.yaml
.github/workflows/build-docker-image-rosetta.yaml
Makefile

fix: revert ubuntu 22 builds

---

x/reward/keeper/reward_pool.go
x/reward/keeper/reward_pool_test.go

fix(reward)!: clear rewards if validator is no longer bonded on releasing rewards

---

.github/workflows/build-docker-image-and-binaries.yaml
.github/workflows/build-docker-image-rosetta.yaml
.github/workflows/build-latest-docker-image.yaml
.github/workflows/check-go-generate.yaml
.github/workflows/check-internal-deps.yaml
.github/workflows/check-proto-generate.yaml
.github/workflows/enforce-evm-migration.yaml
.github/workflows/lint.yaml
.github/workflows/release-dry-run.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
Makefile

This reverts commit 99fcea0f943f2a8a4882ce4af26eb0bcd0ff331a.
We'll bump back to Ubuntu 22 once we document and test the appropriate steps that need to be taken to upgrade.

revert: "chore: update github runner to ubuntu-22.04 (#1689)"

---

x/vote/keeper/poll.go

Use the cached passing weight for the poll

refactor(vote): use cached passing weight

---

x/evm/types/types.go
x/nexus/keeper/transfer.go

fix(nexus)!: fix recipient address validation

---

go.mod
go.sum
x/evm/types/types.go

- Split out checks to avoid wrapping nil errors

fix!: event id validation

---

x/axelarnet/module.go
x/axelarnet/module_test.go
x/axelarnet/types/expected_keepers.go
x/axelarnet/types/mock/expected_keepers.go

fix(axelarnet)!: use correct codec

---

x/evm/abci.go
x/evm/abci_test.go

Check deposit status before enqueuing transfer

fix(evm)!: check deposit status before creating transfer

---

app/app.go
x/axelarnet/keeper/address_validator.go
x/axelarnet/keeper/address_validator_test.go
x/axelarnet/types/expected_keepers.go
x/axelarnet/types/mock/expected_keepers.go
x/evm/keeper/address_validator_test.go
x/nexus/keeper/genesis_test.go
x/nexus/keeper/keeper_test.go
x/nexus/keeper/transfer_test.go

check axelar recipient address

fix!: axelar address check

---

go.mod
go.sum

chore: fix internal deps

---

x/nexus/keeper/migrate.go
x/nexus/keeper/migrate_test.go
x/nexus/module.go
x/nexus/types/types.go

feat(nexus): migrate maintainer states

---

app/app.go
go.mod
go.sum
x/axelarnet/handler.go
x/axelarnet/keeper/ibc_transfer.go
x/axelarnet/keeper/msg_server.go
x/axelarnet/keeper/msg_server_test.go
x/axelarnet/module.go
x/axelarnet/module_test.go

refactor(axelarnet): remove transferK in msg server

---

vald/evm/evm.go
vald/evm/evm_test.go
vald/evm/rpc/rpcClient.go
vald/start.go

feat(vald): stop falling back to confirmation for eth2

---

vald/evm/evm.go
vald/evm/evm_test.go
vald/evm/rpc/rpcClient.go
vald/start.go

feat(vald): stop falling back to confirmation for eth2 (#1753)

---

.github/workflows/build-latest-docker-image.yaml

chore: remove latest tag as we have set ecr to immutable

---

.github/workflows/build-latest-docker-image.yaml

chore: remove latest tag as we have set ecr to immutable (#1761)

---

go.mod
go.sum
x/nexus/keeper/keeper_test.go
x/nexus/keeper/transfer.go
x/nexus/keeper/transfer_test.go

Fixes foreign asset check for recipient chain

fix(nexus)!: recipient chain foreign asset check

---

app/app.go
x/evm/keeper/baseKeeper.go

revert(evm): revert init subspace fix

---

Makefile
third_party/proto/proofs.proto
third_party/proto/tendermint/abci/types.proto
third_party/proto/tendermint/types/evidence.proto
third_party/proto/tendermint/types/types.proto

Update tendermint protos to latest version

fix: update tendermint protos

---

utils/bitmap_test.go
vald/config/config.go
vald/start.go

fix(vald): add retries for failing event notifications (#1815)

---

x/evm/abci.go
x/evm/abci_test.go

refactor(evm): make event handling atomic

---

x/evm/abci.go
x/evm/abci_test.go
x/evm/keeper/msg_server.go
x/evm/types/expected_keepers.go
x/evm/types/mock/expected_keepers.go

- Rate limit contract call with token
- Register asset rate limit on deploy token

feat(evm)!: rate limit contract call with token

---

.github/workflows/check-go-generate.yaml

chore: fix gateway artifact download

---

x/nexus/types/codec.go

Register nexus rate limit msg in codec

fix(nexus)!: register rate limit msg in codec

---

x/axelarnet/rate_limit.go
x/axelarnet/rate_limit_test.go
x/axelarnet/types/testutils/types.go

fix(axelarnet): wrong port/channel being used for rate limiting incoming IBC transfer

---

x/axelarnet/module.go

fix(axelarnet)!: rate limit is not called on receive packet

---

app/codec/codec.go

chore: register legacy msg

---

x/nexus/keeper/chain.go
x/nexus/keeper/genesis.go
x/nexus/keeper/genesis_test.go
x/nexus/keeper/grpc_query.go
x/nexus/keeper/transfer.go
x/nexus/keeper/transfer_test.go
x/nexus/types/expected_keepers.go
x/nexus/types/mock/expected_keepers.go

Fee getter returns 0 fee if not a fee is not registered

fix(nexus): fee getter should return default zero value

---

vald/evm/rpc/moonbeam.go

fix(vald): add nil check for latestFinalizedBlockNumber for moonbeam

---

cmd/axelard/cmd/root_test.go
docs/cli/axelard_vald-start.md
vald/start.go

fix(vald): use sync broadcast mode for vald

---

vald/start.go

fix(vald): copy job by value in closure

---

cmd/axelard/cmd/root_test.go
docs/cli/axelard_vald-start.md
vald/config/config.go
vald/start.go
vald/start_test.go

fix(vald): backport vald stall and broadcast mode fix

---

contract-version.json

Update gateway contract version to `v4.3.1`

chore(evm): update gateway version to v4.3.1

---

Makefile

fix: rebuild docker images (#1877)

---

.github/workflows/build-docker-image-and-binaries.yaml

fix(docker): fix creating manifest for multi arch build

---

Dockerfile.debug

fix(dockerfile): add /axelar as safe directory in container to avoid directory ownership issue

---

go.mod
go.sum

cherry-pick no rpc client defined [fix](https://github.com/axelarnetwork/cosmos-sdk/commit/10143b5bd119fb7c17e8a02cfc3ff093ced56e7c) to fork

chore: cherry-pick client fix

---

.github/workflows/build-docker-image-and-binaries.yaml
.github/workflows/build-docker-image-rosetta.yaml
.github/workflows/build-latest-docker-image.yaml
.github/workflows/check-go-generate.yaml
.github/workflows/check-internal-deps.yaml
.github/workflows/check-proto-generate.yaml
.github/workflows/enforce-evm-migration.yaml
.github/workflows/lint.yaml
.github/workflows/release-dry-run.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
Makefile

feat: upgrade build machine OS to ubuntu 20.04

---

.github/workflows/build-docker-image-and-binaries.yaml
.github/workflows/build-docker-image-rosetta.yaml
.github/workflows/build-latest-docker-image.yaml
.github/workflows/check-go-generate.yaml
.github/workflows/check-internal-deps.yaml
.github/workflows/check-proto-generate.yaml
.github/workflows/enforce-evm-migration.yaml
.github/workflows/lint.yaml
.github/workflows/release-dry-run.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
Makefile

* feat: upgrade os build machine to ubuntu 20.04
* feat: upgrade build machine os to ubuntu 20.04
* feat: upgrade build os to ubuntu 20.04
* feat: update Makefile
---------

feat: upgrade build machine OS to ubuntu 20.04 (#1900)

---

go.mod
go.sum

backport LCD fix in cosmos-sdk #1899

chore: cherry-pick LCD client fix (#1899)

---

vald/evm/evm.go
vald/evm/evm_test.go
vald/evm/rpc/client.go
vald/evm/rpc/ethereum.go
vald/evm/rpc/ethereum_2.go
vald/evm/rpc/mock/client.go
vald/evm/rpc/moonbeam.go
vald/start.go

feat(vald): integrate latest finalized block cache

---

.github/workflows/build-docker-image-and-binaries.yaml

fix: use previous cosign version (#1922)

---

x/axelarnet/keeper/hooks.go
x/axelarnet/keeper/hooks_test.go
x/axelarnet/types/codec.go
x/axelarnet/types/proposal.go
x/axelarnet/types/types.go

fix(axelarnet): some PR comments regarding the call contracts proposal

---

x/evm/types/msg_confirm_gateway_txs.go

chore(evm)!: lower batch confirmation limit

---

app/app.go

fix: move nexus router registration before being passed to axelarnet proposal handler

---

app/app.go
x/axelarnet/handler.go

refactor(axelarnet): improve logging at proposal handler

---

x/axelarnet/module.go
x/axelarnet/module_test.go

fix(axelarnet)!: handle IBC timeout for GMP (#1)

---

go.mod
go.sum

chore(rosetta): staking and pending balance query support

---

x/axelarnet/types/proposal.go

fix(axelarnet)!: pick up gov.ValidateAbstract to validate the proposal title and description

---

x/axelarnet/message_handler.go
x/axelarnet/message_handler_test.go

AXE-1357 block transfer to uppercase GMP account to avoid unintentional transfers

feat(axelarnet)!: block transfer to uppercase GMP account

---

Dockerfile
Makefile

[AXE-1956]
[AXE-1956]: https://axelarnetwork.atlassian.net/browse/AXE-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(makefile): fix non-wasm docker image build with ledger tag

---

x/axelarnet/types/expected_keepers.go
x/axelarnet/types/mock/expected_keepers.go
x/evm/keeper/vote_handler.go
x/evm/keeper/vote_handler_test.go
x/evm/types/expected_keepers.go
x/evm/types/mock/expected_keepers.go
x/nexus/keeper/general_message.go
x/nexus/keeper/general_message_test.go
x/nexus/keeper/msg_dispatcher.go
x/nexus/keeper/msg_dispatcher_test.go
x/nexus/types/expected_keepers.go
x/nexus/types/mock/expected_keepers.go

refactor(nexus): make SetMessageProcessing private and replace it with RouteMessage

---

.github/workflows/build-docker-image-and-binaries.yaml
.github/workflows/build-latest-docker-image.yaml
.github/workflows/take-snapshot.yaml

chore(gh-action): parameterized repo name

---

.github/workflows/build-docker-image-and-binaries.yaml
.github/workflows/build-latest-docker-image.yaml
.github/workflows/take-snapshot.yaml

chore: cherry-pick #2035

---

Makefile

chore: add `MaxWasmSize` to compile flag

---

vald/evm/evm.go
vald/evm/evm_test.go

chore(cherry-pick): cherry pick v0.34.3 patch to release branch

---

vald/evm/evm.go
vald/evm/evm_test.go

* chore: additional vald logging and improvements
* address comment

chore(cherry-pick): cherry pick patch v0.34.3 to main

---

app/app.go

fix: add nexus module account

---

x/evm/abci.go
x/evm/abci_test.go
x/evm/keeper/vote_handler.go
x/evm/keeper/vote_handler_test.go

fix(evm)!: set event status to completed when msg is queued for routing in the nexus module

---

.github/workflows/build-docker-image-and-binaries.yaml

ci: remove arm support for pre-built images/binaries

---

vald/evm/evm.go
vald/evm/evm_test.go
vald/evm/rpc/client.go
vald/evm/rpc/ethereum.go
vald/evm/rpc/mock/client.go
vald/evm/rpc/mock/ethereum.go
x/evm/types/events.go

fix(vald): broadcast empty vote for failed txs (#2100)

---

vald/evm/evm.go
vald/evm/evm_test.go

fix(vald): panic when confirming gateway txs and tx is not finalized

---

.github/workflows/build-docker-image-and-binaries.yaml

fix: remove dash before use in r2 upload step for build docker workflow

---

go.mod
go.sum

chore: backport archival query fix #2125

---

Makefile
app/app.go
app/app_test.go
app/keepers.go
app/wasm_test.go

[AXE-3589]
[AXE-3589]: https://axelarnetwork.atlassian.net/browse/AXE-3589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(Makefile)!: set max wasm code size correctly

---

sdk-utils/broadcast/broadcast_test.go

fix: make broadcast batching test deterministic

---

Makefile

[AXE-4511]
[AXE-4511]: https://axelarnetwork.atlassian.net/browse/AXE-4511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix!: enable cosmwasm 1_1 and 1_2 capabilities

---

x/axelarnet/handler.go
x/axelarnet/handler_test.go
x/axelarnet/message_handler.go
x/evm/keeper/vote_handler.go
x/evm/keeper/vote_handler_test.go

[AXE-4570]
[AXE-4570]: https://axelarnetwork.atlassian.net/browse/AXE-4570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(axelarnet)!: allow routing messages from gov module to wasm

---

vald/evm/evm.go
vald/evm/rpc/client.go

fix(vald): extend type API to reduce underlying ambiguity

---

go.mod
go.sum

- **fix(sdk): valid dec range (#2211)**

fix(sdk): valid dec range

---

x/nexus/keeper/general_message.go
x/nexus/keeper/msg_id_generator.go

refactor(nexus): rename nextID to currIDAndIncr and update the doc

---

go.mod
go.sum

point to [commit](https://github.com/axelarnetwork/cosmos-sdk/commit/523fb865146c258a09b940dc34e12bcdc141fe1f)

chore: sdk deps update

---

go.mod
go.sum

chore(deps)!: bump up comsmwasm dependencies

---

Dockerfile
go.mod

chore: bump up wasmvm version in dockerfile

---

app/app.go
app/migrate_module_account.go
app/migrate_module_account_test.go

fix(auth)!: migrate the distribution account to have burner permission

---

client/docs/yarn.lock

Resolve security issues:
- https://github.com/axelarnetwork/axelar-core/security/dependabot/59
- https://github.com/axelarnetwork/axelar-core/security/dependabot/54
- https://github.com/axelarnetwork/axelar-core/security/dependabot/52
- https://github.com/axelarnetwork/axelar-core/security/dependabot/44
- https://github.com/axelarnetwork/axelar-core/security/dependabot/58
- https://github.com/axelarnetwork/axelar-core/security/dependabot/55
- https://github.com/axelarnetwork/axelar-core/security/dependabot/47
- https://github.com/axelarnetwork/axelar-core/security/dependabot/46
- https://github.com/axelarnetwork/axelar-core/security/dependabot/45

chore(docs): maintain yarn.lock for client docs

---

app/wasm.go
app/wasm_test.go

fixes https://github.com/axelarnetwork/axelar-core/pull/2253#discussion_r2185249415, https://github.com/axelarnetwork/axelar-core/pull/2253#discussion_r2185278051 and https://github.com/axelarnetwork/axelar-core/pull/2253#discussion_r2190319979

fix: check for any message instead of stargate

---

.github/CODEOWNERS
.github/workflows/build-binaries-and-push-to-r2.yaml
.github/workflows/build-docker-image-and-binaries.yaml
.github/workflows/build-latest-docker-image.yaml
.github/workflows/check-go-generate.yaml
.github/workflows/check-internal-deps.yaml
.github/workflows/check-proto-generate.yaml
.github/workflows/conventional-commits.yml
.github/workflows/enforce-evm-migration.yaml
.github/workflows/lint.yaml
.github/workflows/packaging.yaml
.github/workflows/release-dry-run.yaml
.github/workflows/release.yaml
.github/workflows/take-snapshot.yaml
.github/workflows/test.yaml
.github/workflows/testnet-catch-up.yml
client/docs/yarn.lock
go.mod
go.sum
x/axelarnet/keeper/hooks.go
x/axelarnet/keeper/hooks_test.go
x/nexus/keeper/wasm_querier.go

fixes some bugs with the 0.50 upgrade
just opening as a draft for visibility

fix: SDK 0.50 update fixes
